deploy_quay_on_openshift/master.adoc

Added Kube prerequisite file to assembly

---

modules/attributes.adoc
modules/rn_3_10.adoc

Need to update release notes and rebuild all books for Quay 3.1.3 release.

 Updated RN and attributes for 3.1.3 release

---

modules/proc_deploy-quay-openshift-operator.adoc

Corrected routeHost and configRouteHost properties

---

modules/proc_deploy-quay-openshift-operator.adoc

Corrected the Quay configuration password from quay-config to quayconfig.

fixed quayconfig password

---

modules/con_quay_intro.adoc

https://issues.redhat.com/browse/PROJQUAY-293

PROJQUAY-293 - update local storage wording

---

modules/attributes.adoc
modules/rn_1_12.adoc
modules/rn_1_13.adoc
modules/rn_1_14.adoc
modules/rn_1_15.adoc
modules/rn_1_16.adoc
modules/rn_1_17.adoc
modules/rn_1_18.adoc
modules/rn_2_00.adoc
modules/rn_2_10.adoc
modules/rn_2_20.adoc
modules/rn_2_30.adoc
modules/rn_2_40.adoc
modules/rn_2_50.adoc
modules/rn_2_60.adoc
modules/rn_2_70.adoc
modules/rn_2_80.adoc
modules/rn_2_90.adoc
modules/rn_3_00.adoc
modules/rn_3_10.adoc
modules/rn_3_20.adoc

(cherry picked from commit 36a082ad449f70768a6a52441efb483440dbe604)

RN for 3.2.2 and added producty attribute (#42)

---

modules/rn_3_30.adoc

Remove note until PROJQUAY-666 is verified fixed.

PROJQUAY-455 - remove cert note PROJQUAY-666

---

manage_quay/master.adoc
modules/proc_quay-bridge-operator.adoc

Documented the Quay Bridge Operator.

Documented Quay Bridge Operator per PROJQUAY-335

---

modules/proc_container-security-operator-setup.adoc

Added a command for adding a custom cert to CSO.

Documented how to add certs to CSO per PROJQUAY-174

---

modules/proc_deploy-quay-openshift-operator.adoc

Many changes based on diffs from upstream docs between version used for RH Quay v3.2 Setup Operator and Red Hat Quay 3.3 Operator. Also included some changes from https://github.com/redhat-cop/quay-operator/pull/225.

Updated per changes to upstream quay operator

---

Makefile
modules/con_quay_ha_prereq.adoc
modules/proc_deploy-quay-openshift-operator.adoc
modules/rn_3_30.adoc

Cherry picked PRs 66, 68, 69 from master.

More cherry pics

---

modules/proc_deploy-quay-openshift-operator.adoc

Update a deprecated Local Development command in quay-operator docs

---

modules/attributes.adoc

https://issues.redhat.com/browse/PROJQUAY-688

PROJQUAY-688 - qui-gon sprint release

---

modules/attributes.adoc
modules/rn_3_30.adoc

https://issues.redhat.com/browse/PROJQUAY-774

PROJQUAY-774 - 3.3.1 changes

---

modules/proc_deploy_quay_single.adoc
use_quay/master.adoc

Corrected wrong product title attribute from {product-title} to {productname}. Removed a broken link to Redis container image description.

Fixed BZ1859507 and BZ1859463

---

modules/proc_deploy-quay-openshift-operator.adoc
modules/rn_3_30.adoc

(cherry picked from commit b4df54132c83a2af2ea1e1019a23f6879aa13da0)

Fixed osOptions for swift per PROJQUAY-837 (#86)

---

deploy_quay_on_openshift_op_tng/master.adoc

Realized I didn't have a link to old operator docs- worth keeping in for upstream folks on old operator.

Added link to previous operator docs

---

modules/proc_deploy-quay-openshift-operator-tng.adoc

Removed kustomize instructions.

Updated override instructions to use envar method

---

modules/proc_deploy_quay_add.adoc

https://github.com/quay/quay-docs/issues/98

fixed broken link to Clair docs in basic deploy guide

---

modules/proc_use-quay-tags.adoc

https://issues.redhat.com/browse/PROJQUAY-1256

PROJQUAY-1256 - correct quay.expires-after

---

Makefile
deploy_quay_on_openshift_op_tng/master.adoc
modules/con_quay_openshift_prereq.adoc
modules/proc_deploy-quay-openshift-operator-tng.adoc

Review Quay Operator docs and ensure they are aligned with docs in the source repository.

TNG Docs Overhaul

---

modules/proc_deploy-quay-openshift-operator-tng.adoc

Updates TNG Operator docs to include instructions on manually migrating external access components.

External Access Manual Migration (PROJQUAY-1345)

---

modules/rn_3_30.adoc

(cherry picked from commit 59929f4e86de472edf90f1af61bb7904f35dc50d)

PROJQUAY-1352 - 3.3.3 release notes (#110)

---

modules/proc_use-quay-build-workers-dockerfiles.adoc

First version of Builder docs- replacing the Google Doc at https://docs.google.com/document/d/1gbXPE-i64hzTQGUBF6bWMs8-HkJM20U6tmrUpCk5H48/edit#
For PROJQUAY-1362

Builder Docs

---

modules/proc_deploy_quay_ha.adoc
modules/proc_deploy_quay_ha_lbdb.adoc
modules/proc_deploy_quay_single.adoc
modules/proc_manage-quay-ssl.adoc
modules/ref_deploy_quay_openshift.adoc

https://issues.redhat.com/browse/PROJQUAY-1229

PROJQUAY-1229 - update redis and psql images

---

modules/rn_3_30.adoc

(cherry picked from commit f4c4fe87ff3da524e122403fb763e001361dd61c)

PROJQUAY-1420 - 3.3.4 release notes

---

modules/rn_3_30.adoc

(cherry picked from commit c31ae19031db9b261abf49313a5cc2ea2b40daee)

PROJQUAY-1420 - correct 3.3.4 release note

---

modules/attributes.adoc

Updated attributes.adoc to bump the product version to 3.3.4

Update product version to 3.3.4

---

manage_quay/docinfo.xml
use_quay/docinfo.xml

Need to fix this to publish downstream "3" docs correctly

Use producty variable for version in docinfo

---

Makefile
modules/attributes.adoc
modules/proc_deploy_quay_add.adoc
modules/proc_deploy_quay_guided.adoc
modules/proc_deploy_quay_single.adoc
modules/proc_manage-advanced-config.adoc
modules/proc_manage-clairv4.adoc
modules/proc_manage-quay-geo-replication.adoc
modules/proc_upgrade_v3.adoc
modules/ref_deploy_quay_openshift.adoc
modules/rn_3_00.adoc

https://issues.redhat.com/browse/PROJQUAY-1431
Updating image references for 3.4.0

PROJQUAY-1431 - update image references

---

modules/proc_use-quay-build-workers-dockerfiles.adoc

Builder Doc Improvements

---

modules/proc_use-quay-build-workers-dockerfiles.adoc

With some extra cosmetic formatting, typos tidy up.

PROJQUAY-1443 Quay image builder docs tidy up

---

.gitignore
deploy_quay/master.adoc
modules/con_quay_intro.adoc
modules/con_quay_openshift_prereq.adoc
modules/con_quay_single_prereq.adoc
modules/proc_deploy_quay_poc_conf.adoc
modules/proc_deploy_quay_poc_db.adoc
modules/proc_deploy_quay_poc_redis.adoc
modules/proc_deploy_quay_poc_rhel.adoc
modules/proc_deploy_quay_poc_run_use.adoc

Adds postgres, podman, removes --privileged, etc

PROJQUAY-1511 Update Deploy Quay Basic doc

---

modules/proc_deploy-quay-openshift-operator-tng.adoc

PROJQUAY-1426 Add AWS CloudFront info

---

modules/con_quay_ha_prereq.adoc
modules/proc_deploy-quay-openshift-operator-tng.adoc
modules/rn_3_40.adoc

Updates TNG doc, release notes and HA prereqs

PROJQUAY-1541 NooBaa graduated from TP to GA

---

modules/proc_deploy-quay-openshift-operator-tng.adoc

Addresses https://issues.redhat.com/browse/PROJQUAY-1577

Include Internal Kubernetes Hostnames as SANs when using Custom TLS

---

modules/rn_3_40.adoc

PROJQUAY-1556 - 3.4.1 release notes

---

modules/con_schema.adoc

https://issues.redhat.com/browse/PROJQUAY-1633

PROJQUAY-1633 - schema doc SECRET_KEYs

---

modules/proc_deploy_quay_poc_conf.adoc
modules/proc_deploy_quay_poc_use.adoc

https://issues.redhat.com/browse/PROJQUAY-1941

PROJQUAY-1941 Missing text

---

modules/proc_deploy-quay-openshift-operator-tng-install.adoc

- use noobaa terminology and support options
- clarify noobaa limitations and alternatives
- provide details around Noobaa backing store

Draft: clarify noobaa usage and terms (WIP)

---

modules/proc_use-quay-create-repo.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-1668
Preview:

PROJQUAY-1668 remove namespace text

---

modules/proc_deploy_quay_add.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-1600
Preview:

PROJQUAY-1600 fixes Clair deployment link

---

modules/proc_manage-clairv4.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-1744
Preview:

PROJQUAY-1744 Updates Clairctl command

---

modules/con_schema.adoc
modules/proc_manage-clairv4.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-1599
Image: https://imgur.com/XpiyiAj

PROJQUAY-1599

---

modules/con_schema.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-1641

PROJQUAY-1641 swaps True for False in Feature Repo Mirror in RHQ Config

---

config_quay/modules

PROJQUAY-2074 Config guide: basic structure and introduction

---

config_quay/master.adoc
modules/config-fields-db.adoc
modules/config-fields-redis.adoc
modules/config-fields-required.adoc
modules/config-fields-scanner.adoc
modules/config-fields-storage.adoc
modules/config-fields-tag-expiration.adoc
modules/config-file-minimal.adoc

PROJQUAY-2074 Config guide: basic structure and introduction 

---

modules/proc_use-api.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-707

PROJQUAY-707 updates create a private repo command

---

modules/attributes.adoc
modules/rn_3_50.adoc

This is the PR for adding 3.5.4 Release Notes for Quay.

Adds Quay version 3.5.4 release notes

---

modules/proc_manage-ldap-setup.adoc

Signed-off-by: Daniel Messer <dmesser@redhat.com>

ldap considerations

---

modules/operator-components-unmanaged-storage.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-2252
Swapping storage/ objectstorage.

Swaps storage/ objectstorage in the quayregistry.yaml

---

deploy_quay_on_openshift_op_tng/master.adoc
modules/config-openshift-editor-reconfigure.adoc

Missed a commit from previous PR

PROJQUAY-2231 Document how to enable monitoring when the Quay Operator is installed in a namespace

---

modules/rn_3_60.adoc

Removes 12383247 in Jira links.

Removes all instances of ?filter=12382147

---

modules/georepl-arch.adoc
modules/georepl-intro.adoc

PROJQUAY-2773 - the original PR was merged to 3.5, and then to 3.6, but the 3.6 merge got wiped. It needs to go onto master first...

PROJQUAY-2498 Quay release notes unclear regarding georeplication and openshift operator

---

modules/attributes.adoc
modules/proc_upgrade_standalone.adoc
modules/rn_3_60.adoc

Projquay 2786

---

modules/rn_3_40.adoc

Adds the 3.4.7 RNs to the 3.4 branch

---

modules/attributes.adoc

Changes the increment version

---

modules/rn_3_40.adoc

PROJQUAY-2785 3.4.7 RNs to master

---

builders-virtual

Adds a rough draft of the Builders procedure

---

modules/other-oci-artifacts-with-quay.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3353

Adds : to OCI artifacts

---

modules/georepl-deploy-operator.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3458

Changes kind: base to kind: quay

---

modules/rn_3_60.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3585

Adds the 3.6.5 release notes

---

modules/attributes.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3585

Updates version to 3.6.5

---

modules/config-fields-misc.adoc
modules/config-fields-ssl.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-2747

Updates two config field parameters

---

modules/clair-openshift-manual.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-1598

Adds feature_security_notifications parameter when setting up Clair

---

modules/quota-management-and-enforcement.adoc
modules/quota-management-limitations.adoc

https://issues.redhat.com/browse/PROJQUAY-3734

Adds limitation sizes of DBs

---

manage_quay/master.adoc
modules/standalone-to-operator-backup-restore.adoc

https://stevsmit.github.io/quay-docs/standalone-migration/html-single/#migrating_a_standalone_red_hat_quay_deployment_to_openshift_container_platform

Adds migration procedure to Quay

---

deploy_quay_on_openshift_op_tng/master.adoc
modules/georepl-deploy-operator.adoc
modules/operator-unmanaged-clair.adoc
modules/restoring-red-hat-quay.adoc

Revert "Red Hat Quay on OCP restructuring"

---

modules/georepl-deploy-operator.adoc

Ticket https://issues.redhat.com/browse/PROJQUAY-4003

Updates geo-rep docs slightly

---

modules/operator-upgrade.adoc
modules/proc_upgrade_standalone.adoc

Preview: 
Issue: https://issues.redhat.com/browse/PROJQUAY-3490

Adds swift config to 3.3 to 3.6 upgrade

---

modules/rn_3_70.adoc

Adds the 3.7.3 RNs.
Issue: https://issues.redhat.com/browse/PROJQUAY-4048

Adds the 3.7.3 RNs

---

modules/georepl-deploy-operator.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4019

Adds feature parameter to geo rep config

---

modules/config-fields-nested-repositories.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4137

Sets feature extended repo names to true by default

---

modules/config-fields-jwt.adoc

https://issues.redhat.com/browse/PROJQUAY-4190

Fixes typo with jwt/jtw config

---

modules/config-fields-jwt.adoc

https://issues.redhat.com/browse/PROJQUAY-4190

Swaps JWT to JTW in 4.6

---

modules/georepl-deploy-operator.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4209
@stevsmit - Kindly review

JIRA#PROJQUAY-4209

---

modules/rn_3_70.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4233

Adds 3.7.5 RNs

---

modules/builders-virtual-environment.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3966

Updates oc get token commands

---

.vscode/settings.json
modules/config-file-intro.adoc
modules/config-file-location.adoc
modules/config-file-minimal.adoc
modules/config-intro.adoc
modules/config-updates-36.adoc
modules/config-updates-37.adoc
modules/rn_3_60.adoc

Chapter 1 only. 
https://stevsmit.github.io/quay-docs/config-ch-1/index.html#config-intro
Just need a quick review to ensure things adhere to IBMSG.
Thanks

Updates the configuration introduction

---

modules/config-fields-misc.adoc

@stevsmit - Here for your review

PROJQUAY3175: Added Default value to pagination size field

---

modules/config-updates-37.adoc
modules/rn_3_70.adoc

https://issues.redhat.com/browse/PROJQUAY-4358

Adds 3.7.7 release notes

---

modules/config-fields-actionlog.adoc
modules/garbage-collection.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-2942

Adds clean blob upload folder

---

deploy_quay_on_openshift_op_tng/master.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4422
Preview:

PROJQUAY4422: Added Backup and restore guide to Operator book

---

modules/config-fields-mirroring.adoc
modules/config-updates-37.adoc
modules/garbage-collection.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4571

Adds a note that explains inactive and expired tags

---

modules/rn_3_80.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4584

Updates a known issue

---

modules/rn_3_80.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4588

Updates a known issue (#510)

---

modules/rn_3_70.adoc

https://issues.redhat.com/browse/PROJQUAY-4357

Updates 377 release notes

---

modules/rn_3_80.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4611
Reference: https://github.com/quay/quay/pull/1554/files

Updates OCI media types

---

modules/operator-unmanaged-postgres.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-3291
Preview: https://snarayan-redhat.github.io/quay-docs/PROJQUAY-3291_pgtrgm/index.html#operator-unmanaged-postgres

PROJQUAY-3291:Added pg_trgm requirements

---

modules/proxy-cache-leveraging-storage-quota-limits.adoc

No issue. Based on https://coreos.slack.com/archives/G7VFPAY7Q/p1666777000120349

Updates proxy cache procedure

---

modules/proc_use-quay-build-workers-dockerfiles.adoc

https://issues.redhat.com/browse/PROJQUAY-3414

Adds job registration timeout to AWS VB docs

---

modules/attributes.adoc
modules/rn_3_70.adoc

Based on https://errata.devel.redhat.com/advisory/103564

Adds 3710 release notes

---

modules/rn_3_80.adoc

https://issues.redhat.com/browse/PROJQUAY-4688

Adds a known issue to the RNs

---

modules/config-fields-basic.adoc

https://issues.redhat.com/browse/PROJQUAY-3173
Preview: https://snarayan-redhat.github.io/quay-docs/PROJQUAY-3173_titledesc/index.html#config-fields-basic

PROJQUAY#3173: Adding description to config fields

---

modules/garbage-collection.adoc

KCS master work: https://docs.google.com/spreadsheets/d/1NTWIfgqbA4CRhdqVvSha3AUtdml3vX0cquYtJNx4wws/edit?hl=en#gid=472934483 
Based on https://access.redhat.com/solutions/6963111

Updates garbage collection guide

---

modules/config-ui-storage-georepl.adoc
modules/rn_3_80.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4802

Adds workaround for QuayRegistry config yaml

---

modules/mirroring-worker.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4795
Cherry pick to 3.7

Updates mirroring worker command when tls is configured

---

modules/georepl-deploy-operator.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-4698

Adds distirbuted storage preference to mirror pods

---

modules/clair-crda-configuration.adoc

Cherry pick to 3.7
Issue: https://issues.redhat.com/browse/PROJQUAY-4824

YAML fix for Clair CRDA

---

modules/config-fields-user.adoc
modules/config-updates-38.adoc

Makes the default setting for FEATURE_SUPERUSERS_FULL_ACCESS false

---

modules/builders-virtual-environment.adoc

https://issues.redhat.com/browse/PROJQUAY-4954

Updates virtual builders docs

---

modules/proc_upgrade_standalone.adoc

https://issues.redhat.com/browse/PROJQUAY-4864

Fixes target images for upgrading

---

modules/georepl-prereqs.adoc

https://issues.redhat.com/browse/PROJQUAY-4996
Cherry pick to 3.7.

updates important message in georep docs

---

modules/clair-standalone-quay-config.adoc
modules/downgrade-quay-deployment.adoc

Adds important note and fixes incorrect security parameter

---

modules/rn_3_80.adoc
release_notes/master.adoc

https://errata.devel.redhat.com/advisory/108869

Adds 382 release notes

---

modules/rn_3_80.adoc

https://issues.redhat.com/browse/PROJQUAY-5090

Updates release note links

---

modules/garbage-collection.adoc

https://issues.redhat.com/browse/PROJQUAY-5071

Fixes clean blob upload folder default setting

---

deploy_quay/master.adoc
modules/clair-standalone-configure.adoc

Includes:
https://issues.redhat.com/browse/PROJQUAY-5084
https://issues.redhat.com/browse/PROJQUAY-5101

Fixes a few nits with the Clair guide

---

modules/rn_3_80.adoc

https://github.com/quay/quay-docs/pull/609

Adds 383 release notes

---

modules/attributes.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-5160
Cherry-pick to 3.7

Updates redis and postgres images

---

modules/operator-unmanaged-storage.adoc

https://issues.redhat.com/browse/PROJQUAY-4755
CP to 3.7.

Updates unamanged storage yamls for rados ceph and hcp

---

modules/quay-as-cache-proxy.adoc

Updates cache proxy to GA

---

modules/builders-virtual-environment.adoc
modules/proc_use-quay-build-workers-dockerfiles.adoc

https://issues.redhat.com/browse/PROJQUAY-4772

Updates minimum retry threshold

---

modules/branding-quay-deployment.adoc
modules/config-fields-redis.adoc
modules/proc_deploy_quay_ha_lbdb.adoc

Includes the following tickets: 
https://issues.redhat.com/browse/PROJQUAY-5201
https://issues.redhat.com/browse/PROJQUAY-5200
https://issues.redhat.com/browse/PROJQUAY-5195

Updates various guides

---

modules/api-organization-validateProxyCacheConfig.adoc

Adds note about known issue when running POST validateproxycache

---

modules/proc_container-security-operator-setup.adoc

https://issues.redhat.com/browse/PROJQUAY-5416

Adds known issue workaround to docs

---

modules/georepl-prereqs.adoc

Removes organization from list of geo rep capabilities

---

modules/operator-volume-size-overrides.adoc

https://issues.redhat.com/secure/Dashboard.jspa?selectPageId=12333818

Work on 4301

---

config_quay/master.adoc
modules/config-envvar-dbpool.adoc
modules/config-envvar-georepl.adoc
modules/config-envvar-intro.adoc
modules/config-envvar-worker-connection.adoc
modules/config-envvar-worker-count.adoc

https://issues.redhat.com/browse/PROJQUAY-5159

Adds debug env variables to config guide

---

deploy_quay_ha/master.adoc
deploy_quay_on_openshift_op_tng/master.adoc
modules/upgrading-geo-repl-quay-operator.adoc
modules/upgrading-geo-repl-quay.adoc
upgrade_quay/master.adoc

HA:https://stevsmit.github.io/quay-docs/ha/#upgrading-highly-available-quay
Operator: https://stevsmit.github.io/quay-docs/operator-upgrade/#upgrading-highly-available-quay-operator

Provides procedure to upgrade a HA deployment of Quay

---

config_quay/master.adoc
modules/config-fields-nutanix.adoc
modules/config-fields-storage-swift.adoc

https://issues.redhat.com/browse/PROJQUAY-5396

Adds nutanix storage reference

---

manage_quay/master.adoc
modules/rn_3_90.adoc
modules/using-v2-ui.adoc
use_quay/master.adoc

https://stevsmit.github.io/quay-docs/ui-v2/#using-v2-ui

Adds UI changes to 39

---

modules/proc_manage-ldap-setup.adoc
modules/rn_3_90.adoc

https://issues.redhat.com/browse/PROJQUAY-5613

Adds known issue fix to 39 RNs

---

modules/builders-virtual-environment.adoc

https://issues.redhat.com/browse/PROJQUAY-5350

Adds CORS GCP procedure

---

modules/configuring-custom-clair-database.adoc

https://issues.redhat.com/browse/PROJQUAY-5640

Updates clair key cert file names

---

modules/ssl-trust-ca-system.adoc

https://issues.redhat.com/browse/PROJQUAY-5583

Updates link

---

manage_quay/master.adoc
modules/health-check-quay.adoc

https://issues.redhat.com/browse/PROJQUAY-5161

Adds health check endpoints docs

---

modules/running-quay-debug-mode-operator.adoc
modules/running-quay-debug-mode.adoc
modules/troubleshooting-forgotten-passwords.adoc
modules/troubleshooting-slow-pushes.adoc
troubleshooting_quay/master.adoc

Based on https://access.redhat.com/solutions/6998868

Adds troubleshooting info

---

modules/error-502-troubleshooting.adoc
troubleshooting_quay/master.adoc

Based on: https://access.redhat.com/solutions/6998878

502 error kcs

---

modules/mirrored-images-unable-pull-rhocp.adoc
troubleshooting_quay/master.adoc

https://access.redhat.com/solutions/6966410

Removes duplicative modules

---

manage_quay/master.adoc
modules/config-fields-actionlog.adoc
modules/monitoring-single-namespace.adoc
modules/operator-customize-images.adoc
modules/operator-deploy-infrastructure.adoc
modules/operator-resize-storage.adoc
modules/proc_generating-splunk-token.adoc
modules/proc_installing-creating-username-splunk.adoc
modules/proc_manage-log-storage-elasticsearch.adoc
modules/proc_manage-log-storage-splunk.adoc
modules/proc_splunk-action-log.adoc
modules/proc_splunk-config.adoc
modules/rn_3_90.adoc

https://issues.redhat.com/browse/PROJQUAY-5058
Preview: https://stevsmit.github.io/quay-docs/splunk

Proc splunk 1

---

deploy_red_hat_quay_operator/master.adoc
modules/config-preconfigure-automation.adoc
modules/config-updates-39.adoc
modules/mapping-repositories-to-cpe-information.adoc
modules/operator-components-managed.adoc
modules/operator-components-unmanaged.adoc
modules/operator-managed-postgres.adoc
modules/operator-upgrade.adoc
modules/rn_3_90.adoc
modules/upgrading-postgresql.adoc

https://issues.redhat.com/browse/PROJQUAY-5277
Based on https://docs.google.com/document/d/11utb5woUEqpzxtIlE59ZQWhKHbD3f6vhUj7YWsfHVY4/edit

PostgreSQL feature work for 3.9

---

modules/proc_upgrade_standalone.adoc

Revert "Adds postgresql data migration procedure"

---

welcome.adoc

Revert "hoping to fix some test branch issues"

---

welcome.adoc

change to welcome

---

welcome.adoc

Revert "change to welcome"

---

.github/workflows/preview.yml

Revert "Test yaml change"

---

CNAME

Revert "adding cname"

---

.github/workflows/preview.yml

Revert "adding welcome to preview.yml"

---

deploy_quay_on_openshift_op_tng/master.adoc
deploy_red_hat_quay_operator/master.adoc

https://issues.redhat.com/browse/PROJQUAY-5993
CP 3.8

Moves SSL/TLS content

---

modules/clair-updater-urls.adoc
modules/clair-updaters.adoc
modules/clair-vulnerability-scanner-hosts.adoc
modules/config-fields-clair-matchers.adoc
modules/config-fields-overview.adoc
modules/config-fields-required-intro.adoc

https://issues.redhat.com/browse/PROJQUAY-6062
https://issues.redhat.com/browse/PROJQUAY-6052
https://issues.redhat.com/browse/PROJQUAY-6061

Enriches clair documentation to add components and URLs

---

modules/georepl-prereqs.adoc
modules/operator-georepl-site-removal.adoc
modules/proc_manage-upgrade-quay-guide.adoc
red_hat_quay_operator_features/master.adoc

https://issues.redhat.com/browse/PROJQUAY-5944

Updates important admonition in georepl site removal docs

---

modules/proc_upgrade_standalone.adoc
modules/standalone-to-operator-backup-restore.adoc

minor-build-fixes

---

modules/backing-up-red-hat-quay-operator.adoc
modules/builders-virtual-environment.adoc
modules/clair-disconnected.adoc
modules/fips-overview.adoc
modules/georepl-intro.adoc
modules/mapping-repositories-to-cpe-information.adoc
modules/monitoring-single-namespace.adoc
modules/operator-cloudfront.adoc
modules/operator-config-ui-access.adoc
modules/operator-customize-images.adoc
modules/operator-ipv6-dual-stack.adoc
modules/operator-upgrade.adoc
modules/rn_3_10_0.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-6452

IBM Power and Z documentation for Quay

---

welcome.adoc

Revert "Adds Quay IO to downstream docs"

---

modules/managing-namespace-auto-pruning-policies.adoc
modules/rn_3_10_0.adoc
modules/rn_3_11_0.adoc
modules/rn_3_80.adoc
modules/rn_3_90.adoc
modules/using-v2-ui.adoc

https://issues.redhat.com/browse/PROJQUAY-6687

Adds procedure and feature for UI v2 dark mode

---

modules/rn_3_11_0.adoc

Jira: https://issues.redhat.com/browse/PROJQUAY-6940

Document a known issue for IBM Power and Z

---

modules/rn_3_11_0.adoc
modules/upgrading-geo-repl-quay-operator.adoc

https://issues.redhat.com/browse/PROJQUAY-6978
https://issues.redhat.com/browse/PROJQUAY-6872

Updates a few docs issues to close a few PRs

---

modules/clair-standalone-configure.adoc

https://issues.redhat.com/browse/PROJQUAY-6871

Updates port of Clair postgresql db

---

modules/config-fields-storage-noobaa.adoc
modules/config-fields-storage-rados.adoc

https://issues.redhat.com/browse/PROJQUAY-7232
Cherry pick to 3.11

Adds new parameters for Ceph and RHOCS storage drivers

---

modules/oidc-config-fields.adoc

CP to 3.11.
https://issues.redhat.com/browse/PROJQUAY-7263

Adds OIDC disable user endpoint

---

modules/proc_splunk-action-log.adoc

https://issues.redhat.com/browse/PROJQUAY-2632

Adds example log entries

---

modules/config-fields-overview.adoc

Fixes some Clair exporting commands

---

modules/configuring-resources-managed-components.adoc
modules/proc_use-quay-view-export-logs.adoc
modules/viewing-usage-logs-v2-ui.adoc

Revert "Fixes CPU error"

---

modules/config-fields-tag-expiration.adoc
modules/creating-image-expiration-notification.adoc
modules/creating-notifications-api.adoc
modules/creating-notifications.adoc
modules/rn_3_12_0.adoc
use_quay/master.adoc

https://issues.redhat.com/browse/PROJQUAY-6977

Starts work on event trigger feature

---

modules/rn_3_12_0.adoc

Jira: https://jsw.ibm.com/browse/POCPQE-133

IBM Power/Z documentation for Quay 3.12

---

modules/georepl-intro.adoc
modules/rn_3_13_0.adoc

Issue: https://issues.redhat.com/browse/PROJQUAY-8172
Draft: https://docs.google.com/document/d/1eLmSkxHdWt4xRlaq_AvskgGy1tW3EKkPwtLJB1JAa5o/edit?tab=t.0

Documentation updated for IBM Power and IBM Z

---

modules/attributes.adoc
modules/rn_3_13_0.adoc

https://errata.devel.redhat.com/advisory/145473
https://issues.redhat.com/browse/PROJQUAY-8528

Adds 3.13.4 release notes

---

modules/attributes.adoc
modules/rn_3_10_0.adoc

https://errata.devel.redhat.com/advisory/144399 
https://issues.redhat.com/browse/PROJQUAY-8529

Adds 3108 rns

---

modules/attributes.adoc
modules/rn_3_13_0.adoc

Revert "removes 3134 rns"

---

modules/clair-disconnected.adoc

Version(s): 3.14
Jira Issue : https://issues.redhat.com/browse/PROJQUAY-8754

IBM P/Z Quay 3.14 Release

---

modules/rn_3_14_0.adoc

Jira Issue: https://issues.redhat.com/browse/PROJQUAY-8677

[PROJQUAY-8677] IBM P/Z pgBouncer remove support

---

modules/setting-tag-expirations-v2-ui.adoc

Covers https://issues.redhat.com/browse/PROJQUAY-8312 and https://issues.redhat.com/browse/PROJQUAY-1607

Adds annotations label to docs

---

modules/mapping-repositories-to-cpe-information.adoc

Jira Issue : https://issues.redhat.com/browse/PROJQUAY-8806

[PROJQUAY-8806]IBM P/Z Quay Common Product Enumeration Supported from 3.14 Release

---

modules/config-disclaimer.adoc

https://issues.redhat.com/browse/PROJQUAY-4277

Slight modification to configuration disclaimer

---

modules/attributes.adoc
modules/config-ui-mirroring.adoc
modules/mirroring-creating-repo.adoc
modules/mirroring-working-with.adoc
modules/rn_3_15_0.adoc

https://issues.redhat.com/browse/PROJQUAY-9287

Adds 3.15.1 release notes and mirroring feature
