quay/quay-docs

modules/attributes.adoc, modules/rn_3_10.adoc
Updated release notes and attributes file (with version number). All books need to be rebuilt because of the attribute change
=> Updated RN and attributes for 3.1.2 release

manage_quay/master.adoc, modules/ref_deploy_quay_openshift.adoc
A quay container lacked a "v" for the version number. clair-jwt lacked the version attribute.
=> Fix missing two incorrect container versions.

modules/attributes.adoc, modules/rn_3_20.adoc
Add release notes description for Quay 3.2.1 and updated attributes so all references to the current version (on things like quay containers) use 3.2.1
=> Updated RN and attributes to Quay 3.2.1

modules/proc_deploy_quay_add.adoc, modules/proc_deploy_quay_openshift.adoc, modules/proc_deploy_quay_single.adoc, modules/proc_use-api.adoc
Fixed the following Jira in this PR:
- Update docs with cert mount path for repo mirroring: https://issues.redhat.com/browse/PROJQUAY-5
- more detailed firewall explanations in basic quay install docs please: https://issues.redhat.com/browse/PROJQUAY-245
- Quay config secret missing word “config” in documentation: https://issues.redhat.com/browse/PROJQUAY-410
- Document running swagger for api exploration: https://issues.redhat.com/browse/PROJQUAY-425
Please also check these Jira, which were previously fixed for Quay 3.2, but never closed:
- Add details on how to use Quay API: https://issues.redhat.com/browse/PROJQUAY-409
- Documentation missing flag --privileged=true for quay-builder command: https://issues.redhat.com/browse/PROJQUAY-413
- Document the CSO: …
=> Closed small Quay 3.2 bugs

modules/attributes.adoc, modules/rn_1_12.adoc, modules/rn_1_13.adoc, modules/rn_1_14.adoc, modules/rn_1_15.adoc, modules/rn_1_16.adoc, modules/rn_1_17.adoc, modules/rn_1_18.adoc, modules/rn_2_00.adoc, modules/rn_2_10.adoc, modules/rn_2_20.adoc, modules/rn_2_30.adoc, modules/rn_2_40.adoc, modules/rn_2_50.adoc, modules/rn_2_60.adoc, modules/rn_2_70.adoc, modules/rn_2_80.adoc, modules/rn_2_90.adoc, modules/rn_3_00.adoc, modules/rn_3_10.adoc, modules/rn_3_20.adoc
Added release notes entry for 3.2.2. Updated attributes to add "producty" attribute, which allows the y-stream release number to be set and used in URLs to the docs.
=> RN for 3.2.2 and added producty attribute

modules/proc_use-quay-build-workers-dockerfiles.adoc
Updated the "docker run" command for running quay-builder to add :Z to the end of the mount of docker.sock within the container. This should cause SELinux file labeling to work properly on that item. The resulting fix will be published here: https://access.redhat.com/documentation/en-us/red_hat_quay/3.2/html-single/use_red_hat_quay/index#run-the-build-worker-image and on the 3.3 version as well.
=> Added :Z to docker.sock mount per PROJQUAY-113

modules/rn_3_30.adoc
This clarifies a particular release note that was potentially misleading and found to be non-obvious to QE.
=> Enhance phrasing on a single Quay Operator v3.3.0 release note

deploy_quay_on_openshift_op/master.adoc, modules/con_deploy_quay_start_using.adoc, modules/con_quay_intro.adoc, modules/con_quay_openshift_prereq.adoc, modules/proc_deploy-quay-openshift-operator.adoc
Updated the guide for deploying Red Hat Quay on OpenShift using the "Quay Operator" (formerly the Quay Setup Operator). This update included the addition of descriptions for doing post-deployment Quay updates using either the Quay Config Tool or the Quay Operator itself. This update also includes an extensive upgrade description.
=> Updated Quay Operator deployment per PROJQUAY-334

modules/con_schema.adoc, modules/proc_deploy_quay_add.adoc, modules/proc_deploy_quay_guided.adoc, modules/proc_deploy_quay_openshift.adoc, modules/proc_manage-clair-enable.adoc, modules/proc_manage-clairv4.adoc, modules/proc_manage-ldap-setup.adoc, modules/proc_manage-quay-geo-replication.adoc, modules/proc_manage-quay-ssl.adoc, modules/proc_manage-repomirror.adoc, modules/proc_manage-security-scanning.adoc, modules/proc_manage-upgrade-quay-guide.adoc, modules/proc_manage-upgrade-quay.adoc, modules/proc_use-quay-tags.adoc, modules/rn_1_13.adoc
I fixed a bunch of small issues after doing a final read-through of the Red Hat Quay 3.3 docs. These includes some broken links, typos, and old references to the previous superuser panel.
=> Final editing pass after publishing Quay 3.3

deploy_quay_on_openshift_op_tng/master.adoc, modules/con_quay_openshift_prereq.adoc, modules/proc_deploy-quay-openshift-operator-tng.adoc
The manual steps needed to prepare the database for migration are no longer necessary with https://github.com/quay/quay-operator/pull/374.
=> Remove Manual QuayEcosystem Database Migration Steps (PROJQUAY-1363)

modules/proc_use-quay-build-workers-dockerfiles.adoc
Adds the workaround to the limitation that OpenShift `Routes` cannot serve more than one port, so a second `Route` must be created to serve traffic to the build manager on the gRPC port.
=> OpenShift Route Limitations with Builders (PROJQUAY-1418)

modules/proc_use-quay-build-workers-dockerfiles.adoc
We forgot to add it to the Quay Operator section.
=> Document Adding Build Cluster Certs to `configBundleSecret`

modules/proc_deploy-quay-openshift-operator-tng-advanced.adoc
It is [no longer necessary](https://github.com/quay/quay-operator/pull/406) to include the internal Kubernetes hostnames as SANs of the provided cert/key pair (which was impossible using PKI).
=> Remove Need for SANs in Operator Deployed Quay (PROJQUAY-1737)

modules/proc_manage-quay-prometheus.adoc
Cherry-picked from https://github.com/quay/quay-docs/pull/243 for https://issues.redhat.com/browse/PROJQUAY-2475.
=> Fixes Prometheus endpoint port in 3.4

modules/proc_manage-quay-prometheus.adoc
For https://issues.redhat.com/browse/PROJQUAY-2475
Should be cherry-picked to 3.4.
=> Fixes Prometheus endpoint port in 3.5

modules/rn_3_60.adoc
Release Notes for 3.6. 
This PR includes the following Jira Issues: 
https://issues.redhat.com/browse/PROJQUAY-2294
https://issues.redhat.com/browse/PROJQUAY-2526
https://issues.redhat.com/browse/PROJQUAY-2527
https://issues.redhat.com/browse/PROJQUAY-2523
https://issues.redhat.com/browse/PROJQUAY-2423
https://issues.redhat.com/browse/PROJQUAY-1950
https://issues.redhat.com/browse/PROJQUAY-2481
=> PROJQUAY-RNs 3.6

welcome.adoc
❗ IMPORTANT: this needs to go in along with https://github.com/quay/quay/pull/884 so we avoid broken links in our docs.
Update links and wording of getting started for both evaluation and development docs on Github.
=> welcome: update getting started links to reflect changes on Quay repo (PROJQUAY-2500)

modules/backing-up-and-restoring-intro.adoc, modules/backing-up-red-hat-quay.adoc, modules/restoring-red-hat-quay.adoc
- replace hard-coded product names with variable
- better structure for backup/restore of several components
- comprehensive instructions to scale down/up all required Quay components
- more reliable wait conditions
=> refining backup and restore procedures

config_quay/master.adoc, modules/config-fields-modelcache.adoc, modules/config-fields-redis.adoc, modules/config-file-minimal.adoc, modules/operator-unmanaged-redis.adoc
Issue: https://issues.redhat.com/browse/PROJQUAY-3888
=> Adds Redis configuration to docs

manage_quay/master.adoc, modules/backing-up-red-hat-quay-operator.adoc, modules/backing-up-red-hat-quay-standalone.adoc, modules/restoring-red-hat-quay-standalone.adoc, modules/restoring-red-hat-quay.adoc, modules/standalone-deployment-backup-restore.adoc
https://stevsmit.github.io/quay-docs/backup-restore/index.html
Please note that I have *not* tested this. I do not have a standalone deployment of Red Hat Quay. **This is just a draft. I am aware some content might require revision**.
The last backup/restore procedure there were many changes between QE and PM (Daniel). By submitting this prior to attempting it myself, I'm hoping to avoid multiple iterations of re-writes.
Preview: https://stevsmit.github.io/quay-docs/backup-restore/index.html#standalone-deployment-backup-restore
Issue: https://issues.redhat.com/browse/PROJQUAY-3108
Based on the following instructions given to me by Ivan: https://docs.google.com/document/d/1QizE6IShRWf36ToxuE-V1yxf3u9xrz4b_xttAipHa9A/edit
=> Adds backup and restore for standalone

modules/config-fields-user.adoc, modules/config-updates-38.adoc, modules/rn_3_80.adoc
Issue: https://issues.redhat.com/browse/PROJQUAY-4671
=> Updates the FEATURE_RESTRICTED_USERS config value

api/master.adoc, modules/api-definitions.adoc, modules/api-mirror-changeRepoMirrorConfig.adoc, modules/api-mirror-createRepoMirrorConfig.adoc, modules/config-fields-mirroring.adoc, modules/external-registry-config-api-example.adoc, modules/root-rule-config-api-example.adoc
Issues:
https://issues.redhat.com/browse/PROJQUAY-3758
https://issues.redhat.com/browse/PROJQUAY-4742
Preview: https://stevsmit.github.io/quay-docs/api-example/index.html#external-registry-config-api-example
=> Adds mirror config fields to config docs

modules/proc_container-security-operator-setup.adoc
=> Updates cso information

modules/proxy-cache-arch.adoc, modules/quay-as-cache-proxy.adoc
https://issues.redhat.com/browse/PROJQUAY-5052
=> Fixes a few errors in the Use Red Hat guide

clair/master.adoc, modules/config-fields-clair-auth.adoc, modules/config-fields-clair-indexer.adoc, modules/config-fields-clair-matcher.adoc, modules/config-fields-clair-matchers.adoc, modules/config-fields-clair-metrics.adoc, modules/config-fields-clair-notifiers.adoc, modules/config-fields-clair-trace.adoc, modules/config-fields-clair-updaters.adoc, modules/config-fields-general-clair.adoc, modules/config-fields-overview.adoc
https://issues.redhat.com/browse/PROJQUAY-4883
=> Updates clair book to add configuration fields

config_quay/master.adoc, manage_quay/master.adoc, modules/branding-quay-deployment.adoc, modules/config-fields-basic.adoc, modules/config-fields-branding.adoc, modules/proc_creating-ocp-secret-for-oauth-token.adoc, modules/proc_creating-quay-integration-cr.adoc, modules/proc_installing-qbo-on-ocp.adoc, modules/proc_setting-up-quay-for-qbo.adoc, modules/ref_quay-integration-config-fields.adoc
https://issues.redhat.com/browse/PROJQUAY-3212
=> Updates registry title and registry title short config descriptions

modules/config-fields-scanner.adoc
I'm submitting this PR because I found that **SECURITY_SCANNER_INDEXING_INTERVAL** configuration parameter is duplicated inside the documentation
Link to [docs](https://access.redhat.com/documentation/en-us/red_hat_quay/3/html-single/configure_red_hat_quay/index#config-fields-scanner)
=> Removed duplicate configuration parameter

modules/clair-openshift-airgap-database-standalone.adoc, modules/clair-openshift-airgap-database.adoc
cpe-map.json and repo-map.json files are not properly read due to the incorrect indentation. This in return caused a failure in Clair to scan images and it took a while to figure out why.
=> changes to modules/clair-openshift-airgap-database.adoc, fixed indentation

modules/enabling-team-sync-oidc.adoc
https://issues.redhat.com/browse/PROJQUAY-7128
=> Updates team sync proc

deploy_red_hat_quay_operator/master.adoc, modules/creating-custom-ssl-certs-config-bundle.adoc, modules/operator-config-cli-download.adoc, modules/operator-custom-ssl-certs-config-bundle.adoc, modules/ssl-create-certs.adoc
https://issues.redhat.com/browse/PROJQUAY-7623
=> Updates SSL cert proc for Operator docs

modules/config-fields-ldap.adoc
Starting with Quay 3.12 there was a new configuration option added called LDAP_GLOBAL_READONLY_SUPERUSER_FILTER. When the documentation for this feature was originally written(0b0eabbc338c472f0dba3be30baeb06e46cf5b6e) it was incorrectly called GLOBAL_READONLY_SUPER_USERS.
Initial feature added to Quay here https://github.com/quay/quay/pull/2917. Reference to code in latest commit on redhat-3.12 branch https://github.com/quay/quay/blob/2c4c7570513b6dd205f7ce53ec25716baac45d85/data/users/__init__.py#L72-L74.
ref: https://issues.redhat.com/browse/PROJQUAY-7044
=> Fix Typo In LDAP Configuration Docs

modules/config-fields-ldap.adoc
Starting with Quay 3.12 there was a new configuration option added called LDAP_GLOBAL_READONLY_SUPERUSER_FILTER. When the documentation for this feature was originally written(0b0eabbc338c472f0dba3be30baeb06e46cf5b6e) it was incorrectly called GLOBAL_READONLY_SUPER_USERS.
Initial feature added to Quay here https://github.com/quay/quay/pull/2917. Reference to code in latest commit on redhat-3.12 branch https://github.com/quay/quay/blob/2c4c7570513b6dd205f7ce53ec25716baac45d85/data/users/__init__.py#L72-L74.
ref: https://issues.redhat.com/browse/PROJQUAY-7044
This is a cherry-pick of commit 6dceb39045289e232ab8fa702b551a907b7771ed
=> Quay 3.13: Fix Typo In LDAP Configuration Docs

modules/config-fields-ldap.adoc
Starting with Quay 3.12 there was a new configuration option added called LDAP_GLOBAL_READONLY_SUPERUSER_FILTER. When the documentation for this feature was originally written(0b0eabbc338c472f0dba3be30baeb06e46cf5b6e) it was incorrectly called GLOBAL_READONLY_SUPER_USERS.
Initial feature added to Quay here https://github.com/quay/quay/pull/2917. Reference to code in latest commit on redhat-3.12 branch https://github.com/quay/quay/blob/2c4c7570513b6dd205f7ce53ec25716baac45d85/data/users/__init__.py#L72-L74.
ref: https://issues.redhat.com/browse/PROJQUAY-7044
This is a cherry-pick of commit 6dceb39045289e232ab8fa702b551a907b7771ed
=> Quay 3.12: Fix Typo In LDAP Configuration Docs

modules/setting-tag-expiration-api.adoc
The example looks like a copy/paste from another place and was not updated. Fix the payload to match was expected.
=> set expiration through API: fix example

modules/con_quay_ha_prereq.adoc
The name of the Crunchy Data operator is "Postgres Operator" and not "CrunchDB Operator". "CrunchyDB" does not exist, so this simple patch fixes the documentation to accurately reflect that.
@stevsmit
=> Fix for 'Postgres Operator' product name
